[project]
name = "latex-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "customtkinter>=5.2.2",
    "jinja2>=3.1.6",
    "pillow>=12.0.0",
    "pyperclip>=1.11.0",
    "rich>=14.2.0",
]
